root = "."
tmp_dir = "tmp"

[build]
cmd = "make"
bin = "tmp/main.exe"
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "public"]
include_dir = [
    "cmd",
    "routes",
    "views",
    "handlers",
    "gintemplaterenderer",
    "utils",
]
exclude_regex = ["_test.go"]
exclude_file = []
exclude_unchanged = true
log = "air.log"
args_bin = []
stop_on_error = true
send_interrupt = false
delay = 1000
kill_delay = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
